name: Build Windows EXE (CHAP1_v10)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect workdir (run.py location)
        id: wd
        shell: pwsh
        run: |
          if (Test-Path "$pwd/run.py") {
            "workdir=$pwd" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            $candidates = Get-ChildItem -Directory | Where-Object { Test-Path "$($_.FullName)/run.py" }
            if ($candidates.Count -ge 1) {
              "workdir=$($candidates[0].FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            } else {
              "workdir=$pwd" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            }
          }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        working-directory: ${{ steps.wd.outputs.workdir }}
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller==6.10.0

      - name: Clean previous build
        shell: pwsh
        working-directory: ${{ steps.wd.outputs.workdir }}
        run: |
          if (Test-Path CHAP1_v10.spec) { Remove-Item CHAP1_v10.spec -Force }
          if (Test-Path build) { Remove-Item build -Recurse -Force }
          if (Test-Path dist) { Remove-Item dist -Recurse -Force }

      - name: Smoke test imports
        shell: pwsh
        working-directory: ${{ steps.wd.outputs.workdir }}
        run: |
          python -c "import importlib; [importlib.import_module(m) for m in ['PySide6','faster_whisper','soundcard','numpy','pandas','openpyxl','dateparser','_cffi_backend']]; print('OK')"

      - name: Build EXE (CHAP1_v10)
        shell: pwsh
        working-directory: ${{ steps.wd.outputs.workdir }}
        run: |
          python -m PyInstaller `
            --clean --noconfirm --onefile --windowed `
            --paths . `
            --hidden-import _cffi_backend `
            --collect-all PySide6 `
            --collect-all optimisation_pilotage `
            --collect-binaries ctranslate2 `
            --name CHAP1_v10 run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v10_exe
          path: ${{ steps.wd.outputs.workdir }}\dist\CHAP1_v10.exe
