name: Build Windows EXE (CHAP1 2.3 - Clean)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if exist requirements.txt (
            pip install -r requirements.txt
          )

      - name: Build EXE
        shell: pwsh
        run: |
          $args = @('--noconsole','--onefile','--name','CHAP1_v2_3','--add-data','assets;assets','--add-data','data;data')
          if (Test-Path 'assets/chap1.ico') { $args += @('--icon','assets/chap1.ico') }
          $args += 'run.py'
          python -m PyInstaller @args

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v2_3_EXE
          path: dist/CHAP1_v2_3.exe
          if-no-files-found: error
