name: Build Windows EXE (CHAP1_v19_clean)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Ensure folders & placeholders
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path assets | Out-Null
          New-Item -ItemType Directory -Force -Path data | Out-Null
          if (-not (Test-Path data\.gitkeep)) { "" | Out-File -FilePath data\.gitkeep -Encoding ascii }

      - name: Install dependencies (runtime + PyInstaller)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path requirements.txt) {
            python -m pip install -r requirements.txt
          }
          python -m pip install pyinstaller pillow

      - name: Build EXE (no UPX)
        shell: cmd
        run: |
          set ICON=
          if exist assets\chap1.ico set ICON=--icon assets\chap1.ico
          python -m PyInstaller --noconsole --onefile --name CHAP1_v19_clean %ICON% ^
            --hidden-import sounddevice ^
            --hidden-import faster_whisper ^
            --hidden-import ctranslate2 ^
            --collect-all faster_whisper ^
            --collect-all ctranslate2 ^
            --collect-all sounddevice ^
            --collect-submodules numpy ^
            --exclude-module numpy.tests ^
            --exclude-module pip ^
            --add-data "assets;assets" ^
            --add-data "data;data" ^
            run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v19_clean
          path: dist/CHAP1_v19_clean.exe
