name: Build Windows EXE (CHAP1_v21)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: bash
        run: |
          ICON="assets/chap1.ico"
          if [ ! -f "$ICON" ]; then ICON=""; fi
          if [ -n "$ICON" ]; then ICON_ARG="--icon $ICON"; else ICON_ARG=""; fi
          python -m PyInstaller --noconsole --onefile --name CHAP1_v21 $ICON_ARG --add-data "assets;assets" run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v21_EXE
          path: dist/CHAP1_v21.exe
          if-no-files-found: error
