
name: Build Windows EXE (CHAP1 2.3.1 + UPX)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path 'requirements.txt') {
            pip install -r requirements.txt
          }

      - name: Build normal
        shell: pwsh
        run: |
          $args = @('--noconsole','--onefile','--name','CHAP1_v2_3_1','--add-data','assets;assets','--add-data','data;data','--add-data','exports;exports','--add-data','logs;logs','--add-data','autosave;autosave')
          if (Test-Path 'assets/chap1.ico') { $args += @('--icon','assets/chap1.ico') }
          $args += 'run.py'
          python -m PyInstaller @args

      - name: Install UPX
        shell: pwsh
        run: |
          choco install upx -y --no-progress
          $env:Path += ';C:\\ProgramData\\chocolatey\\bin;C:\\ProgramData\\chocolatey\\lib\\upx\\tools'
          upx --version

      - name: Build UPX
        shell: pwsh
        run: |
          $args = @('--noconsole','--onefile','--name','CHAP1_v2_3_1_upx','--add-data','assets;assets','--add-data','data;data','--add-data','exports;exports','--add-data','logs;logs','--add-data','autosave;autosave')
          if (Test-Path 'assets/chap1.ico') { $args += @('--icon','assets/chap1.ico') }
          $args += 'run.py'
          python -m PyInstaller @args

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v2_3_1_RELEASE
          path: |
            dist/CHAP1_v2_3_1.exe
            dist/CHAP1_v2_3_1_upx.exe
          if-no-files-found: error
