name: Build Windows EXE (CHAP1 2.2 - Full)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path 'requirements.txt') {
            pip install -r requirements.txt
          }

      - name: Build EXE
        run: |
          $args = @('--noconsole','--onefile','--name','CHAP1_v2_2','run.py')
          if (Test-Path 'assets/chap1.ico') { $args = @('--noconsole','--onefile','--name','CHAP1_v2_2','--icon','assets/chap1.ico','run.py') }
          if (Test-Path 'assets') { $args = $args[0..($args.Count-2)] + @('--add-data','assets;assets') + $args[-1] }
          if (Test-Path 'data')   { $args = $args[0..($args.Count-2)] + @('--add-data','data;data')   + $args[-1] }
          Write-Host "PyInstaller args: $args"
          python -m PyInstaller @args

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v2_2_EXE
          path: dist/CHAP1_v2_2.exe
          if-no-files-found: error
