name: Build Windows EXE (CHAP1 2.3 - Full)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow
          if (Test-Path 'requirements.txt') {
            pip install -r requirements.txt
          }

      - name: Prepare icon (PNG -> ICO if needed)
        run: |
          if (-not (Test-Path 'assets/chap1.ico') -and (Test-Path 'assets/chap1.png')) {
            python - << 'PY'
from PIL import Image
img = Image.open('assets/chap1.png').convert('RGBA')
img.save('assets/chap1.ico', sizes=[(256,256),(128,128),(64,64),(32,32),(16,16)])
print('ICO created from PNG')
PY
          }

      - name: Build EXE
        run: |
          $args = @('--noconsole','--onefile','--name','CHAP1_v2_3')
          if (Test-Path 'assets/chap1.ico') { $args += @('--icon','assets/chap1.ico') }
          if (Test-Path 'assets') { $args += @('--add-data','assets;assets') }
          if (Test-Path 'data')   { $args += @('--add-data','data;data') }
          $args += 'run.py'
          python -m PyInstaller @args

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v2_3_EXE
          path: dist/CHAP1_v2_3.exe
          if-no-files-found: error
