name: Build Windows EXE (CHAP1_v22)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install pyinstaller pillow

      # Use PowerShell here-string to generate a Python script (no bash heredoc)
      - name: Convert provided PNG to ICO
        shell: pwsh
        run: |
          $code = @"
from PIL import Image
img = Image.open("assets/chap1_provided.png").convert("RGBA")
sizes = [(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)]
img.save("assets/chap1.ico", sizes=sizes)
print("ICO created at assets/chap1.ico")
"@
          $code | Set-Content -Path convert_ico.py -Encoding UTF8
          python convert_ico.py

      - name: Install UPX (try Chocolatey, else fallback)
        shell: pwsh
        run: |
          try { choco install upx -y; $UPX=(Get-Command upx).Source } catch { $UPX=$null }
          if (-not $UPX) {
            $url = "https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip"
            $zip = "$env:TEMP\\upx.zip"
            Invoke-WebRequest -Uri $url -OutFile $zip
            Expand-Archive $zip -DestinationPath $env:TEMP\\upx -Force
            $upxpath = Get-ChildItem $env:TEMP\\upx -Recurse -Filter upx.exe | Select-Object -First 1 -ExpandProperty FullName
            echo "$upxpath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          } else {
            echo (Get-Command upx).Source | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          }

      # Use cmd for PyInstaller so ^ line continuations work reliably
      - name: Build EXE (no UPX on libs, icon set)
        shell: cmd
        run: |
          python -m PyInstaller --noconsole --onefile --name CHAP1_v22 --icon assets/chap1.ico ^
            --noupx ^
            --exclude-module numpy.tests ^
            --exclude-module pip ^
            --add-data "data;data" run.py

      - name: Compress EXE with UPX (safe)
        shell: cmd
        run: |
          upx --best --lzma "dist\CHAP1_v22.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CHAP1_v22
          path: dist/CHAP1_v22.exe
