name: Build Windows EXE (CHAP1 2.4.3 noUPX)
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Prepare folders
      shell: pwsh
      run: |
        foreach ($d in @('assets','data','exports','logs','autosave')) { if (-not (Test-Path $d)) { New-Item -Type Directory -Path $d | Out-Null } }
    - name: Verify entry points
      shell: pwsh
      run: |
        if (-not (Test-Path 'run.py')) { throw 'Missing run.py at repo root' }
        if (-not (Test-Path 'optimisation_pilotage/app.py')) { throw 'Missing optimisation_pilotage/app.py' }
        if (-not (Test-Path 'optimisation_pilotage/__init__.py')) { 'from .app import main' | Out-File -FilePath 'optimisation_pilotage/__init__.py' -Encoding utf8 }
    - name: Build
      shell: pwsh
      run: |
        $args = @('--noconsole','--onefile','--name','CHAP1_v2_4_3','--hidden-import','optimisation_pilotage','--hidden-import','optimisation_pilotage.app','--collect-all','optimisation_pilotage','--collect-all','faster_whisper','--collect-all','ctranslate2','--collect-all','sounddevice','--collect-all','soundfile')
        foreach ($pair in @('assets;assets','data;data','exports;exports','logs;logs','autosave;autosave')) { if (Test-Path ($pair.Split(';')[0])) { $args += @('--add-data', $pair) } }
        if (Test-Path 'assets/chap1.ico') { $args += @('--icon','assets/chap1.ico') }
        $args += 'run.py'
        python -m PyInstaller @args
    - uses: actions/upload-artifact@v4
      with:
        name: CHAP1_v2_4_3_RELEASE_noUPX
        path: dist/CHAP1_v2_4_3.exe
        if-no-files-found: error
